import tkinter
import tkinter.font
class Application(tkinter.Frame):
    def __init__ (self,master):
        tkinter.Frame.__init__(self,master)
        self.config(bg="black")
        self.pack()
        self.CreateWidgets()
        
    def CreateWidgets(self):
        self.label1=tkinter.Label(self)
        self.label1.config(text="THE 10 COMMANDMENTS\n")
        self.label1.config(fg="yellow")
        self.label1.config(bg="black")
        self.myFont=tkinter.font.Font(family="Lucida Calligraphy",size=20,weight=tkinter.font.BOLD)
        self.label1.config(font = self.myFont)
        self.label1.pack()
        
        self.label2=tkinter.Label(self)
        self.label2.config(text="1. Thou shalt have no other gods before me.\n")
        self.label2.config(fg="yellow")
        self.label2.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label2.config(font = self.myFont)
        self.label2.pack()

        self.label3=tkinter.Label(self)
        self.label3.config(text="2. Thou shalt not make unto thee any graven image.\n")
        self.label3.config(fg="yellow")
        self.label3.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label3.config(font = self.myFont)
        self.label3.pack()

        self.label4=tkinter.Label(self)
        self.label4.config(text="3. Thou shalt not take the name of the Lord thy God in vain.\n")
        self.label4.config(fg="yellow")
        self.label4.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label4.config(font = self.myFont)
        self.label4.pack()

        self.label5=tkinter.Label(self)
        self.label5.config(text="4. Remember the sabbath day, to keep it holy.\n")
        self.label5.config(fg="yellow")
        self.label5.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label5.config(font = self.myFont)
        self.label5.pack()

        self.label6=tkinter.Label(self)
        self.label6.config(text="5. Honour thy father and thy mother:\n")
        self.label6.config(fg="yellow")
        self.label6.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label6.config(font = self.myFont)
        self.label6.pack()

        self.label7=tkinter.Label(self)
        self.label7.config(text="6. Thou shalt not kill.\n")
        self.label7.config(fg="yellow")
        self.label7.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label7.config(font = self.myFont)
        self.label7.pack()

        self.label8=tkinter.Label(self)
        self.label8.config(text="7. Thou shalt not commit adultery.\n")
        self.label8.config(fg="yellow")
        self.label8.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label8.config(font = self.myFont)
        self.label8.pack()

        self.label9=tkinter.Label(self)
        self.label9.config(text="8. Thou shalt not steal.\n")
        self.label9.config(fg="yellow")
        self.label9.config(bg="black")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label9.config(font = self.myFont)
        self.label9.pack()

        self.label10=tkinter.Label(self)
        self.label10.config(text="9. Thou shalt not bear false witness against thy neighbour.\n")
        self.label10.config(bg="black")
        self.label10.config(fg="yellow")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label10.config(font = self.myFont)
        self.label10.pack()

        self.label11=tkinter.Label(self)
        self.label11.config(text="10. Thou shalt not covet .\n")
        self.label11.config(bg="black")
        self.label11.config(fg="yellow")
        self.myFont=tkinter.font.Font(family="Segoe Script",size=10,weight=tkinter.font.NORMAL)
        self.label11.config(font = self.myFont)
        self.label11.pack()


root=tkinter.Tk()
app=Application(master=root)
app.mainloop()
root.destroy()
